service: loopi
runtime: go122

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.65

env_variables:
  SERVER_PORT: "8080"
  DB_INSTANCE_CONNECTION: "quotes-api-100:us-east1:quotes-instance"
  DB_USER: "loopi-user"
  DB_PASSWORD: "7:Z\"I3=9,(VCU1R+"
  APP_ENV: "production"
  JWT_SECRET: "y4mmCP+GXmkNogRwxzqBKuNO72j29fkr4T65wzCN5Ug="
  JWT_EXPIRATION_HOURS: "24"
  TZ: "America/Bogota"
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  SERVICE_NAME: "loopi-api"
  SERVICE_VERSION: "1.0.0"
  SERVICE_ENV: "production"

handlers:
  - url: /.*
    script: auto
    secure: always
