-- ============================================
-- LOOPI - Seed Data for Testing
-- ============================================

-- Insert test employees (password: password123)
-- Hash generated with bcrypt cost 12
INSERT INTO employees (username, password_hash, name, last_name, role, active) VALUES
('juan', '$2a$12$D//C9pn3XMjsdyitDF6Me.pmXYb4Rkq3BRb5WvrMEv5qs6es12LJS', 'Juan', 'García', 'employee', 1),
('maria', '$2a$12$D//C9pn3XMjsdyitDF6Me.pmXYb4Rkq3BRb5WvrMEv5qs6es12LJS', 'María', 'López', 'admin', 1);

-- Insert all items (products and supplies)
INSERT INTO items (type, name, active) VALUES
('product', 'Cafe Paz x 250gr', 1),
('product', 'Cafe Organico x 250gr', 1),
('product', 'Café Typica x250g', 1),
('product', 'Cafe Gesha 250gr', 1),
('product', 'Cafe Oso 250gr', 1),
('product', 'Cafe Descafeinado x 250gr', 1),
('product', 'Café Pacamara x250g', 1),
('product', 'Paz Filtrado x gr x 1500gr (Caneca)', 1),
('product', 'Filtrado Espresso x 9000gr (Caneca)', 1),
('product', 'CF-SPO gr CAFÉ ORGANICO SABANALARGA x gr x 1500gr', 1),
('product', 'Torta De Zanahoria y Naranja', 1),
('product', 'Torta Chocolate Porcion', 1),
('product', 'Torta Amapola', 1),
('product', 'Torta Red Velvet', 1),
('product', 'Almojabana', 1),
('product', 'Galleta Red Velvet', 1),
('product', 'Galleta Chips Chocolate', 1),
('product', 'Brownie De Chocolate y Nueces', 1),
('product', 'Blondie', 1),
('product', 'Palito Queso x 5', 1),
('product', 'Croissant 3 Quesos x 6', 1),
('product', 'Croissant Jamon y Queso x 6', 1),
('product', 'Croissant De Mantequilla x 6', 1),
('product', 'Empanada Argentina Carne x5', 1),
('product', 'Empanada Argentina Pollo x5', 1),
('product', 'Empanada Argentina Caprese x5', 1),
('product', 'Jugo de Naranja', 1),
('product', 'Pulpa Jugo Amarillo', 1),
('product', 'Pulpa Mango', 1),
('product', 'Pulpa Fresa', 1),
('product', 'Pulpa Piña', 1),
('product', 'Pulpa Mora', 1),
('product', 'Pulpa Maracuyá', 1),
('product', 'Pulpa Smoothie Verde', 1),
('product', 'Pulpa Smoothie Rojo', 1),
('product', 'Gorra Urbania Café', 1),
('product', 'Gorra Urbania Verde', 1),
('product', 'Mug Urbania', 1),
('product', 'Prensa Francesa Bambu 350', 1),
('product', 'Prensa Francesa Bambu 600', 1),
('product', 'Almendras x6', 1),
('product', 'Avena x6', 1),
('product', 'Entera (bolsas)', 1),
('product', 'Deslactosada (six pack)', 1),
('product', 'Almond Rock', 1),
('product', 'Tableta 99%', 1),
('product', 'Mini', 1),
('product', 'De Origen varios porcentajes', 1),
('product', 'Saborizadas', 1),
('product', 'Miel', 1),
('product', 'Chocolate en Polvo (Lujo)', 1),
('product', 'Chocolate en polvo preparaciones', 1),
('product', 'Helado x 5 litros', 1),
('product', 'Frutos Rojos', 1),
('product', 'Frutos Amarillos', 1),
('product', 'Alma Verde x10 tisanas', 1),
('product', 'Jardín Mágico Morada x10', 1),
('product', 'Danza Frutal Amarillo x10', 1),
('product', 'Bosque Sagrado Rojo x10', 1),
('product', 'Chai 500', 1),
('product', 'Vanilla Chai (frasco)', 1),
('product', 'Miel 250g', 1),
('product', 'Miel 150g', 1),
('product', 'Cascara con jenjibre', 1),
('product', 'Cascara sin azucar', 1),
('product', 'Cascara con azúcar', 1),
('product', 'Tea negro Tropical x80g (Tarrito)', 1),
('product', 'Tea Verde Mangostino x80g', 1),
('product', 'Tea Jengibre rojo 80g', 1),
('product', 'Tea Negro Frambuesa x80g', 1),
('product', 'Tea Verde Matcha x80g', 1),
('product', 'Leche en polvo 900g', 1),
('product', 'Leche condesada 800g', 1),
('product', 'Arequipe 1000g', 1),
('product', 'Almidon x 1000g', 1),
('product', 'Azúcar', 1),
('product', 'Cocoa', 1),
('product', 'Oreo', 1),
('product', 'Chantilly', 1),
('product', 'Mantequilla almendras', 1),
('product', 'Azucar Pulverizada', 1),
('product', 'Panela x 200 sobres', 1),
('product', 'Azúcar x2500', 1),
('product', 'Almidon Yuca x1000', 1),
('product', 'Panela x500gr', 1),
('product', 'Milo x2500', 1),
('product', 'Azúcar Pulverizada x1000', 1),
('product', 'Canela x500g', 1),
('product', 'Leche en Polvo x900', 1),
('product', 'Azúcar sobre x200', 1),
('product', 'Splenda x700 sobres', 1),
('product', 'Mantequilla de Almendras x1000', 1),
('supply', 'Vaso 4 onzas Urbania x und', 1),
('supply', 'Vasos 9 Onzas Urbania x und', 1),
('supply', 'Vasos 7 Onzas Urbania x und', 1),
('supply', 'Vaso 7oz x 50 Bioempacol', 1),
('supply', 'Vaso 9oz x 50 Bioempacol', 1),
('supply', 'Vaso 12oz x 50 Bioempacol', 1),
('supply', 'Vaso 16oz Bioempacol', 1),
('supply', 'Vaso 4oz x50 Verde (Urbania)', 1),
('supply', 'Vaso 7oz x50 Verde (Urbania)', 1),
('supply', 'Vaso 9oz x25 Rosado (Urbania)', 1),
('supply', 'Vaso 9oz x25 Bioempacol', 1),
('supply', 'Vaso 16oz (Transparente) x50', 1),
('supply', 'Tapa Viajera 9 Onzas Urbania x und', 1),
('supply', 'Tapa Viajera 7 Onzas Urbania x und', 1),
('supply', 'Tapa 16oz', 1),
('supply', 'Tapa 7oz x 50 Blancas', 1),
('supply', 'Tapa 9oz x 50 Blancas (Urbania)', 1),
('supply', 'Tapa 12 oz x 50 Verde (Bioempacol)', 1),
('supply', 'Tapa 16 oz x 50 Transparente (Bioempacol)', 1),
('supply', 'Servilletas', 1),
('supply', 'Pitillos x200 Bioempacol', 1),
('supply', 'Mezcladores', 1),
('supply', 'Porta comida pequeño', 1),
('supply', 'Mallas para el cabello', 1),
('supply', 'Cucharas', 1),
('supply', 'Bolsas de papel Urbania', 1),
('supply', 'Bolsas papel #1 (para llevar)', 1),
('supply', 'Bolsas papel #3 (para llevar) x 100', 1),
('supply', 'Bolsas Basura', 1),
('supply', 'Jabón platos', 1),
('supply', 'Portavasos (bandeja para llevar)', 1),
('supply', 'Cucharas x 50', 1),
('supply', 'Aisladores (Urbania) x 100', 1),
('supply', 'Porta comida grande (para llevar)', 1),
('supply', 'Porta comida pequeño (para llevar) x 20', 1),
('supply', 'Bandeja pequeña (blanca) x20', 1),
('supply', 'Bandeja grande (blanca) x 20', 1),
('supply', 'Bolsas Urbania', 1),
('supply', 'Filtros Bunn x 500UN', 1),
('supply', 'Pitillos x200', 1),
('supply', 'Servilletas x100', 1),
('supply', 'Cajas KIT', 1),
('supply', 'Filtros V60', 1),
('supply', 'Filtros Aeropress', 1),
('supply', 'Filtros Chemex', 1);
