-- Seed data for items table
-- Generated from items.csv with corrections

-- Clear existing data
TRUNCATE TABLE items;

-- Reset auto_increment
ALTER TABLE items AUTO_INCREMENT = 1;

-- Insert items (type: product)
INSERT INTO items (type, name, active, inventory_frequency) VALUES
('product', 'Cafe Paz x 250gr', 1, 'daily'),
('product', 'Cafe Jaguares x 250gr', 1, 'daily'),
('product', 'Cafe Organico x 250gr', 0, 'daily'),
('product', 'Café Typica x250g', 0, 'daily'),
('product', 'Cafe Gesha 250gr', 0, 'daily'),
('product', 'Cafe Oso 250gr', 0, 'daily'),
('product', 'Cafe Descafeinado x 250gr', 1, 'daily'),
('product', 'Café Pacamara x250g', 0, 'daily'),
('product', 'Paz Filtrado x gr x 1500gr (Caneca)', 1, 'weekly'),
('product', 'Filtrado Espresso x 9000gr (Caneca)', 1, 'weekly'),
('product', 'CF-SPO gr CAFÉ ORGANICO SABANALARGA x gr x 1500gr', 0, 'weekly'),
('product', 'Torta De Zanahoria y Naranja', 1, 'daily'),
('product', 'Torta Chocolate Porcion', 1, 'daily'),
('product', 'Torta Amapola', 0, 'daily'),
('product', 'Torta Red Velvet', 0, 'daily'),
('product', 'Almojabana', 1, 'daily'),
('product', 'Galleta Red Velvet', 1, 'daily'),
('product', 'Galleta Chips Chocolate', 1, 'daily'),
('product', 'Brownie De Chocolate y Nueces', 1, 'daily'),
('product', 'Palito Queso x 5', 1, 'daily'),
('product', 'Croissant 3 Quesos x 6', 1, 'daily'),
('product', 'Croissant Jamon y Queso x 6', 1, 'daily'),
('product', 'Croissant De Mantequilla x 6', 1, 'daily'),
('product', 'Empanada Argentina Carne x5', 1, 'daily'),
('product', 'Empanada Argentina Pollo x5', 1, 'daily'),
('product', 'Empanada Argentina Caprese x5', 1, 'daily'),
('product', 'Jugo de Naranja', 0, 'weekly'),
('product', 'Pulpa Jugo Amarillo', 1, 'weekly'),
('product', 'Pulpa Smoothie Verde', 1, 'weekly'),
('product', 'Pulpa Smoothie Rojo', 1, 'weekly'),
('product', 'Gorra Urbania Café', 0, 'monthly'),
('product', 'Gorra Urbania Verde', 0, 'monthly'),
('product', 'Mug Urbania', 1, 'monthly'),
('product', 'Prensa Francesa Bambu 350', 1, 'monthly'),
('product', 'Prensa Francesa Bambu 600', 1, 'monthly'),
('product', 'Leche de Almendras x6', 1, 'monthly'),
('product', 'Leche de Avena x6', 1, 'monthly'),
('product', 'Leche Entera (bolsas)', 1, 'weekly'),
('product', 'Leche Deslactosada (six pack)', 1, 'weekly'),
('product', 'Almond Rock', 1, 'monthly'),
('product', 'Tableta 99%', 1, 'monthly'),
('product', 'Tableta Mini', 1, 'monthly'),
('product', 'Tableta de origen varios porcentajes', 1, 'monthly'),
('product', 'Tableta saborizadas', 1, 'monthly'),
('product', 'Tableta de miel', 1, 'monthly'),
('product', 'Chocolate en Polvo (Lujo)', 1, 'monthly'),
('product', 'Chocolate en polvo preparaciones', 1, 'monthly'),
('product', 'Helado x 5 litros', 1, 'weekly'),
('product', 'Infusión Frutos Rojos', 1, 'monthly'),
('product', 'Infusión Frutos Amarillos', 1, 'monthly'),
('product', 'Aromática Alma Verde x10 tisanas', 1, 'monthly'),
('product', 'Aromática Jardín Mágico Morada x10', 1, 'monthly'),
('product', 'Aromática Danza Frutal Amarillo x10', 1, 'monthly'),
('product', 'Aromática Bosque Sagrado Rojo x10', 1, 'monthly'),
('product', 'Chai 500g', 1, 'monthly'),
('product', 'Vanilla Chai (frasco)', 1, 'monthly'),
('product', 'Miel 250g', 1, 'monthly'),
('product', 'Miel 150g', 1, 'monthly'),
('product', 'Soda Cascara con jenjibre', 1, 'monthly'),
('product', 'Soda Cascara sin azucar', 1, 'monthly'),
('product', 'Soda Cascara con azúcar', 1, 'monthly'),
('product', 'Tea negro Tropical x80g (Tarrito)', 1, 'monthly'),
('product', 'Tea Verde Mangostino x80g', 1, 'monthly'),
('product', 'Tea Jengibre rojo 80g', 1, 'monthly'),
('product', 'Tea Negro Frambuesa x80g', 1, 'monthly'),
('product', 'Tea Verde Matcha x80g', 1, 'monthly'),
('product', 'Leche en polvo 900g', 1, 'monthly'),
('product', 'Leche condesada 800g', 1, 'monthly'),
('product', 'Arequipe 1000g', 1, 'monthly'),
('product', 'Cocoa', 1, 'monthly'),
('product', 'Chantilly', 1, 'monthly'),
('product', 'Mantequilla almendras', 1, 'monthly'),
('product', 'Panela x 200 sobres', 1, 'monthly'),
('product', 'Azúcar x2500', 1, 'monthly'),
('product', 'Almidon Yuca x1000', 1, 'monthly'),
('product', 'Panela x500gr', 1, 'monthly'),
('product', 'Milo x2500', 1, 'monthly'),
('product', 'Azúcar Pulverizada x1000', 1, 'monthly'),
('product', 'Canela x500g', 1, 'monthly'),
('product', 'Azúcar sobre x200', 1, 'monthly'),
('product', 'Splenda x700 sobres', 1, 'monthly'),
('product', 'Mantequilla de Almendras x1000', 1, 'monthly');

-- Insert items (type: supply)
INSERT INTO items (type, name, active, inventory_frequency) VALUES
('supply', 'Vaso 7oz x 50 Genérico', 1, 'monthly'),
('supply', 'Vaso 9oz x 50 Genérico', 1, 'monthly'),
('supply', 'Vaso 12oz x 50 Genérico', 1, 'monthly'),
('supply', 'Vaso 16oz Genérico', 1, 'monthly'),
('supply', 'Vaso 4oz x50 Verde (Urbania)', 1, 'weekly'),
('supply', 'Vaso 7oz x50 Verde (Urbania)', 1, 'weekly'),
('supply', 'Vaso 9oz x25 Rosado (Urbania)', 1, 'weekly'),
('supply', 'Vaso 16oz (Transparente) x50', 1, 'weekly'),
('supply', 'Tapa Viajera 9 Onzas Urbania x und', 1, 'weekly'),
('supply', 'Tapa Viajera 7 Onzas Urbania x und', 1, 'weekly'),
('supply', 'Tapa 16oz', 1, 'weekly'),
('supply', 'Tapa 7oz x 50 Blancas', 1, 'weekly'),
('supply', 'Tapa 9oz x 50 Blancas (Urbania)', 1, 'weekly'),
('supply', 'Servilletas', 1, 'weekly'),
('supply', 'Pitillos x200 Genérico', 1, 'weekly'),
('supply', 'Mezcladores', 1, 'monthly'),
('supply', 'Porta comida pequeño', 1, 'monthly'),
('supply', 'Mallas para el cabello', 1, 'monthly'),
('supply', 'Bolsas de papel Urbania', 1, 'weekly'),
('supply', 'Bolsas papel #1 (para llevar)', 1, 'monthly'),
('supply', 'Bolsas papel #3 (para llevar) x 100', 1, 'monthly'),
('supply', 'Bolsas Basura', 1, 'weekly'),
('supply', 'Jabón platos', 1, 'monthly'),
('supply', 'Portavasos (bandeja para llevar)', 1, 'monthly'),
('supply', 'Cucharas x 50', 1, 'monthly'),
('supply', 'Aisladores (Urbania) x 50', 1, 'monthly'),
('supply', 'Porta comida grande (para llevar)', 1, 'monthly'),
('supply', 'Porta comida pequeño (para llevar) x 20', 1, 'monthly'),
('supply', 'Bandeja pequeña (blanca) x20', 1, 'monthly'),
('supply', 'Bandeja grande (blanca) x 20', 1, 'monthly'),
('supply', 'Filtros Bunn x 500UN', 1, 'monthly'),
('supply', 'Cajas KIT', 1, 'monthly'),
('supply', 'Filtros V60', 1, 'monthly'),
('supply', 'Filtros Aeropress', 1, 'monthly'),
('supply', 'Filtros Chemex', 1, 'monthly');

-- Verify counts
SELECT 
    type,
    inventory_frequency,
    COUNT(*) as total
FROM items
GROUP BY type, inventory_frequency
ORDER BY type, inventory_frequency;
